title: Settings
data:
  site_name: 'aeffchentoet – das Magazin fuer toete aeffchen'
  personality: casual
  show_signup: true
  social:
    -
      name: Twitter
      url: 'https://twitter.com/'
      icon: site/social-icons/twitter.svg
    -
      name: Github
      url: 'https://github.com/mainetcare/aeffchentoet'
      icon: site/social-icons/github.svg
    -
      name: Email
      url: 'mailto:kartoffelsalat-mit-essig-oel-dressing@aeffchentoet.de'
      icon: site/social-icons/email.svg
